apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KingJessie/gitops-helm-platform.git
    targetRevision: main
    path: helm/argo-rollouts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true