apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-dashboard
  namespace: argo-rollouts
spec:
  selector:
    app.kubernetes.io/name: argo-rollouts-dashboard
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100