server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443

configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance

  rbac:
    policy.default: role:readonly