rbacConfig:
  policy.csv: |
    g, admin, role:admin
  policy.default: role:readonly

server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443

configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance

redis:
  enabled: true

nameOverride: argocd